### ----------------------------------------------
### 4. 🔐 Auth Module
### ----------------------------------------------
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "adminkhoi",
  "name": "Admin Xịn",
  "email": "luongkhoi3456@gmail.com",
  "password": "123456",
  "phone": "0909000111"
}

### Xác minh email (Verify Email)
POST  http://localhost:5000/auth/verify-email
Content-Type: application/json

{
  "token": "05b96ecb335ae744fe8bf36636fdd06c9822f01fc8879ab1995728a0d1f3ea7c"
}

### Đăng nhập (Login)
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "luongkhoi3456@gmail.com",
  "password": "123456",
  "token": "05b96ecb335ae744fe8bf36636fdd06c9822f01fc8879ab1995728a0d1f3ea7c"
}
### Get all categories
GET http://localhost:5000/categories
Accept: application/json

### Create a new category
POST http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

{
  "name": "Bánh ngọt",
  "image": "http://example.com/images/banhngot.jpg"
} 

### Delete a category by ID
DELETE http://localhost:5000/categories/6935379a25d81cbff3156c6d
Accept: application/json

### Get all products
GET http://localhost:5000/products
Accept: application/json

### Create a new product
POST http://localhost:5000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

{
  "name": "Bánh kem socola",
  "description": "Bánh kem socola thơm ngon, mềm mịn.",
  "price": 250000,
  "category": "693538a033982cd7d751c39f",
  "images": [{
    "url": "http://example.com/images/banhkem.jpg",
    "public_id": "banhkem123"
  }],
  "stock": 20
}

### Update a product by ID
PUT http://localhost:5000/products/69353cd6432c6aa83d4e3fc6
Content-Type: application/json

{
  "price": 230000,
  "stock": 25
}

### Delete a product by ID
DELETE http://localhost:5000/products/69353cd6432c6aa83d4e3fc6
Accept: application/json


### 1.4. Lấy thông tin cá nhân (Get Profile)
GET http://localhost:5000/users/profile
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY

### 1.5. Cập nhật thông tin cá nhân (Update Profile)
PUT http://localhost:5000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY

{
  "name": "Nguyễn Văn A",
  "phone": "0912345678",
  "address": "123 Đường ABC, Quận 1, TP.HCM",
  "age": 30
}

### 1.6 Lấy danh sách Users
GET http://localhost:5000/users?limit=1&page=1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY

### 1.7 Khóa tài khoản User
POST http://localhost:5000/users/deactivate/693ac986562377eb07407572
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY

### 1.8 Xoá User
DELETE http://localhost:5000/users/693ac654a519cfbeb8980e23
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY


### 4.1. Tạo đơn hàng (Create Order)
POST http://localhost:5000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

{
  "orderItems": [
    {
      "product": "69353e22b46614ec1f6de822",
      "name": "Bánh kem socola",
      "quantity": 1,
      "image": "url...",
      "price": 250000
    }
  ],
  "shippingAddress": {
    "recipientName": "Nguyen Van A",
    "address": "123 Đường Láng",
    "city": "Hà Nội",
    "phone": "0909090909"
  },
  "paymentMethod": "COD",
  "shippingPrice": 30000,
  "totalPrice": 280000
}

### 4.2. Lấy danh sách đơn hàng của user
GET http://localhost:5000/orders/myorders
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

### 4.3. Lấy chi tiết đơn hàng theo ID
GET http://localhost:5000/orders/694e8868cf26de7d5a98e71a
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

### 4.4. Lay danh sách tất cả đơn hàng (Admin)
GET http://localhost:5000/orders
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

### 4.5. Cập nhật trạng thái đơn hàng (Admin)
PUT http://localhost:5000/orders/694e8868cf26de7d5a98e71a/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NGU4MmFjNjM5MWFkZDc2OTg2MTM2YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzY2NzU0MDEzLCJleHAiOjE3NjkzNDYwMTN9.MlYy3Esvweguq_QzLR-tiPVOS-sOPvopoFZT50n5WFE

{
  "status": "Shipping"
}

### 5.1. Tạo đánh giá cho sản phẩm
POST http://localhost:5000/products/69353e22b46614ec1f6de822/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTM2NzMwNSwiZXhwIjoxNzY3OTU5MzA1fQ.mqhsBspR5-16MvaVGeYjbOu6-gMnerOknQTiFMd4mn4

{
  "rating": 5,
  "comment": "Bánh rất ngon, giao hàng nhanh, đóng gói cẩn thận!"
}

### 5.2. Lấy danh sách đánh giá của sản phẩm
GET http://localhost:5000/products/69353e22b46614ec1f6de822/reviews
Accept: application/json
### 5.3. Lấy danh sách đánh giá pending
GET http://localhost:5000/reviews?status=pending 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTM2NzMwNSwiZXhwIjoxNzY3OTU5MzA1fQ.mqhsBspR5-16MvaVGeYjbOu6-gMnerOknQTiFMd4mn4
### 5.4. Duyệt đánh giá
PUT http://localhost:5000/reviews/69395f757694db2449ae038d/status
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTM2NzMwNSwiZXhwIjoxNzY3OTU5MzA1fQ.mqhsBspR5-16MvaVGeYjbOu6-gMnerOknQTiFMd4mn4

{ 
  "status": "approved" 
}
### 5.5. Reply đánh giá
PUT http://localhost:5000/reviews/69395f757694db2449ae038d/reply 
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTM2NzMwNSwiZXhwIjoxNzY3OTU5MzA1fQ.mqhsBspR5-16MvaVGeYjbOu6-gMnerOknQTiFMd4mn4

{ 
  "reply": "Cảm ơn bạn đã ủng hộ Sweetie Bakery! Shop xin gửi tặng bạn voucher giảm 10% cho đơn sau ạ." 
}

### 6.1. Tạo mã giảm giá
POST http://localhost:5000/coupons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTQ1NDk2NywiZXhwIjoxNzY4MDQ2OTY3fQ.oevFRiYADl-7N_bn95o22NYqJjQIWJwSfIjCni1KtEY

{
  "code": "SALE10",
  "name": "Giảm 10% đón hè",
  "description": "Giảm 10% tối đa 50k cho đơn từ 200k",
  "discountType": "percent",
  "discountValue": 10,
  "maxDiscountAmount": 50000,
  "minOrderValue": 200000,
  "startDate": "2024-01-01",
  "endDate": "2025-12-31",
  "usageLimit": 100
}
### 6.2. Lấy danh sách Coupon
GET http://localhost:5000/coupons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTQ1NDk2NywiZXhwIjoxNzY4MDQ2OTY3fQ.oevFRiYADl-7N_bn95o22NYqJjQIWJwSfIjCni1KtEY
### 6.3. Cập nhật Coupon
PUT http://localhost:5000/coupons/693ab4f6109955d10031d2e4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTQ1NDk2NywiZXhwIjoxNzY4MDQ2OTY3fQ.oevFRiYADl-7N_bn95o22NYqJjQIWJwSfIjCni1KtEY

{
  "name": "Giảm 15% đón hè",
  "discountValue": 15,
  "maxDiscountAmount": 75000
}
### 6.4. Xoá Coupon
DELETE http://localhost:5000/coupons/693ab4f6109955d10031d2e4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTQ1NDk2NywiZXhwIjoxNzY4MDQ2OTY3fQ.oevFRiYADl-7N_bn95o22NYqJjQIWJwSfIjCni1KtEY
### 6.5. Kiểm tra/Áp dụng mã giảm giá
POST http://localhost:5000/coupons/apply
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTMzOTUyNSwiZXhwIjoxNzY3OTMxNTI1fQ.tTpwL-0jIPae4OU0M6B4mHrIOEtyRjEjFn5WgvYyoLY

{
  "code": "SALE50"
}

### 7.1. Upload ảnh
POST http://localhost:5000/upload
Content-Type: multipart/form-data; boundary=MyBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTM0MDQzOCwiZXhwIjoxNzY3OTMyNDM4fQ.0FZGs-xjknviUPzv3hammOLeO32D-cvsUbkd_QOVSYo

--MyBoundary
Content-Disposition: form-data; name="image"; filename="R.jpg"
Content-Type: image/jpeg

< ./R.jpg
--MyBoundary--
### 7.2. Xoá ảnh
DELETE http://localhost:5000/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzhlZWQ4YmMyY2RmMjA2NGNjZjkwYiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NTQ1NjA1MywiZXhwIjoxNzY4MDQ4MDUzfQ.m-VV8tSKOnk3bV9OnWexuz6WpplvQOxpzxeyuTKYwrI

{
  "public_id": "sweetie-bakery-products/nvskrq2aywpikcyw2zmh"
}